name: Build and Test Mojo OSS

on:
  pull_request:

jobs:
  test-pre-submit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: "Get the modular installer, install mojo compiler"
        shell: bash
        run: |
          echo "Downloading the Latest Mojo Compiler"
          curl https://get.modular.com | sh - && modular auth buildAndTestMojoOSS
          modular install mojo
          mojo --version